### ISSUE TITLE
Background not displayed properly

### ISSUE THREAD

**Issue by hackrush01** [hackrushT/HTML-GameInfo#4]
The background is not displayed properly, there is whitespace above and below the background.

**Comment by AnirbanBanik1998** [comment]
Means I have to crop the background image of Sudoku so that the white
spaces are no more there?

**Comment by modihere** [comment]
you have to modify the current repository ..follow the steps given on  [this link](https://gitter.im/hackrushT/Lobby) to clone the repo and start working on it ...don't change the code completely only modify what is needed.

**Comment by parulc7** [comment]
Check out my pull request..
